name: CI to Docker Hub

on: [push, pull_request, workflow_dispatch]

jobs:
  multi:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository: [restic-auto]
        fail-fast: false

    steps:
      - name: Load specific environment
        id: buildenv
        uses: falti/dotenv-action@v0.2.5
        with:
          path: ${{ matrix.repository }}/.build-env

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.repository }}/
          file: ${{ matrix.repository }}/Dockerfile
          platforms: ${{ steps.buildenv.outputs.platforms }}
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.repository }}:latest
